name: "Setup Elixir"
description: "Sets up Elixir and all the caches"

inputs:
  elixir-version:
    required: true
    description: "Elixir version to install"
    default: "1.14"
  otp-version:
    required: true
    description: "Erlang/OTP version to install"
    default: "25.0"
  phoenix-version:
    required: true
    description: "Phoenix Version to use"
    default: "1.7.0"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: "${{ inputs.elixir-version }}"
        otp-version: "${{ inputs.otp-version }}"
    - name: Restore mix deps cache
      uses: actions/cache@v3
      id: mix-cache
      with:
        path: |
          deps
          test_app/deps
          _build
          test_app/_build
          !_build/prod
          !test_app/_build/prod
          priv/plts
        key: mix-${{ runner.os }}-${{ inputs.elixir-version }}-${{ inputs.otp-version }}-${{ inputs.phoenix-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          mix-${{ runner.os }}-${{ inputs.elixir-version }}-${{ inputs.otp-version }}-${{ inputs.phoenix-version }}-
          mix-${{ runner.os }}-${{ inputs.elixir-version }}-${{ inputs.otp-version }}-
    - name: Install Mix Base deps
      shell: bash
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
    - run: mix deps.get
      shell: bash
    - run: mix deps.update phoenix
      shell: bash
    - name: Phoenix Version
      run: mix deps | grep "phoenix "
      shell: bash
